lib/tube_streamer_web/router.ex
defmodule TubeStreamerWeb.Router do
  use TubeStreamerWeb, :router

  pipeline :browser do
    plug :accepts, ["html", "xml"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TubeStreamerWeb.Plug.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :swagger_spec do
    plug :accepts, ["json", "html"]
  end

  scope "/", TubeStreamerWeb do
    pipe_through :browser # Use the default browser stack

    get "/",             PageController, :index
    get "/sitemap.xml",  SitemapController, :index
    get "/stream/:url",  PageController, :stream
  end

  scope "/api", TubeStreamerWeb.Api do
    scope "/v1", V1 do
      pipe_through :api

      get "/stream/:url",   StreamController, :index
      get "/info/:url",     StreamController, :info
    end
  end

  scope "/api" do
    pipe_through :swagger_spec
    scope "/v1" do
      forward "/", TubeStreamerWeb.ApiSwaggerUi.Controller
    end
  end
end

lib/tube_streamer_web/templates/page/index.html.eex
<div class="pull-right">
  <ol class="breadcrumb">
    <li class="<%= is_ru?(@conn) |> active? %>">
      <%= if not is_ru?(@conn) do %>
        <a href="/?locale=ru">Русский</a>
      <% else %>
        Русский
      <% end %>
      </li>
      <li class="<%= is_en?(@conn) |> active? %>">
      <%= if not is_en?(@conn) do %>
        <a href="/?locale=en">English</a>
      <% else %>
        English
      <% end %>
      </li>
  </ol>
</div>

<div class="row"></div>

<div class="jumbotron row">
    <img class="logo" src="<%= static_path(@conn, "/images/logo.jpg") %>">
    <p class="lead">
        <%= gettext "Сервис для получения аудио дорожки с YouTube видео." %>
        <br>
        <%= gettext "Идеально для прослушивания подкастов, микстейпов и скачивания музыки." %>
        <br>
    </p>
</div>

<div class="row">
  <div class="col-md-4 col-sm-4">
  <div class="media">
    <div class="media-left">
      <a href="https://play.google.com/store/apps/details?id=org.nikitenko.youtube_audio">
        <img class="media-object" src="<%= static_path(@conn, "/images/android-logo.png") %>" alt="Android">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= gettext "Android приложение" %></h4>
        <%= gettext "Позволяет слушать аудио поток c YouTube через" %>
        <a href="https://play.google.com/store/apps/details?id=org.nikitenko.youtube_audio">
          <%= gettext "музыкальный проигрыватель." %>
        </a>
        <%= gettext "Работает в фоне и экономит заряд аккамулятора." %>
    </div>
  </div>
  </div>

  <div class="col-md-4 col-sm-4">
  <div class="media">
    <div class="media-left">
      <a href="https://chrome.google.com/webstore/detail/tube-streamer/fcelmhmkblbeajadfgikcicpmgpmpapb">
        <img class="media-object" src="<%= static_path(@conn, "/images/chromewebstore.png") %>" alt="Android">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= gettext "Google Chrome расширение" %></h4>
      <%= gettext "Для получения и" %>
      <a href="https://chrome.google.com/webstore/detail/tube-streamer/fcelmhmkblbeajadfgikcicpmgpmpapb">
        <%= gettext "скачивания" %>
      </a> 
      <%= gettext "аудио стрима через веб-браузер." %>
    </div>
  </div>
  </div>

  <div class="col-md-4 col-sm-4">
  <div class="media">
    <div class="media-left">
      <a href="https://t.me/TubeStreamerBot">
        <img class="media-object" src="<%= static_path(@conn, "/images/telegram-logo.png") %>" alt="Android">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= gettext "Telegram бот" %></h4>
      <%= gettext "Inline бот" %>
      <a href="https://t.me/TubeStreamerBot">@TubeStreamerBot</a> 
      <%= gettext "превратит YouTube видео в аудио стрим." %>
    </div>
  </div>
</div>

lib/tube_streamer_web/templates/page/stream-loading.html.eex
<img id="spinner" src="<%= static_path(@conn, "/images/spinner.gif") %>">
<h3 id="error" style="display: none">Ошибка! Такого стрима тут нет :(</h3>

<script>
  document.addEventListener('DOMContentLoaded', function(){  
    require("js/app.js").Loader.run("<%= @url %>");
  });
</script>

lib/tube_streamer_web/templates/page/stream.html.eex
<img width="240" height="180" src=<%= @cover %>>
<h3><%= @title %></h3>
<audio controls name="media" src=<%= @stream %>></audio>

<br>

<a class="share-logo" href="https://vk.com/share.php?url=<%= page_url @conn, :stream, @id %>" target="_blank">
  <img src="<%= static_path(@conn, "/images/vklogo.png") %>">
</a>
<a class="share-logo" href="https://twitter.com/intent/tweet?text=<%= page_url @conn, :stream, @id %> @tubestreamer" target="_blank">
  <img src="<%= static_path(@conn, "/images/twitterlogo.png") %>">
</a>